version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      ORIGIN: "http://localhost:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000