version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - 5173:5173
    environment:
      PORT: 5173
      ORIGIN: "http://localhost:5173"
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000